name = "Material Docs #2"
license = "MIT"
licenselink = "https://github.com/ipfs/hugo-material-docs/blob/master/LICENSE.md"
description = "A material design theme for documentations."
homepage = "https://github.com/ipfs/hugo-material-docs"
tags = ["material", "documentation", "docs", "search", "offline", "responsive"]
features = []
min_version = 0.30

[author]
  name = "Lars Gierth"
  homepage = "https://github.com/lgierth"

# If porting an existing theme
[original]
  name = "Martin Donath"
  homepage = "http://struct.cc/"
  repo = "https://github.com/squidfunk/mkdocs-material"
